git-debimport postgresql-common_134wheezy4.tar.gz

diff --git a/pg_buildext b/pg_buildext
--- a/pg_buildext
+++ b/pg_buildext
@@ -5,105 +5,93 @@
 #
 # Author: Dimitri Fontaine <dfontaine@hi-media.com>
 
+set -e
+
 action="$1"
-srcdir="$2"
+srcdir="${2:-`pwd`}"
 target="$3"
 opt="$4"
 
+die() {
+    echo "`basename $0`: error: $*" >&2
+    exit 1
+}
+
 prepare_env() {
-    if [ ! -d $srcdir ]; then
-	echo "Error: no such directory '$srcdir'"
-	exit 1
-    fi
     version=$1
-    vtarget=`echo $target | sed -e "s:%v:$version:"`
+    vtarget=`echo $target | sed -e "s:%v:$version:g"`
     pgc="/usr/lib/postgresql/$version/bin/pg_config"
-    cflags=`$pgc --cflags`
+    [ -e "$pgc" ] || die "$pgc does not exists"
+}
+
+configure() {
+    prepare_env $1
+    confopts=`echo $opt | sed -e "s:%v:$version:g"`
+
+    mkdir -p $vtarget
+    ( echo "calling configure in $vtarget" &&
+      cd $vtarget && $srcdir/configure $confopts DESTDIR="$srcdir/debian/$package" PG_CONFIG="$pgc" VPATH="$srcdir" )
 }
 
 build() {
     prepare_env $1
+    cflags="`$pgc --cflags` `echo $opt | sed -e "s:%v:$version:g"`"
 
     mkdir -p $vtarget
-    cd $vtarget
-    make -f $srcdir/Makefile CFLAGS="$cflags $opt" PG_CONFIG="$pgc" VPATH="$srcdir"
-    cd -
+    # if a Makefile was created by configure, use it, else the top level Makefile
+    [ -f $vtarget/Makefile ] || makefile="-f $srcdir/Makefile"
+    make -C $vtarget $makefile CFLAGS="$cflags" DESTDIR="$srcdir/debian/$package" PG_CONFIG="$pgc" VPATH="$srcdir"
+}
+
+install() {
+    prepare_env $1
+    package=`echo $opt | sed -e "s:%v:$version:g"`
+
+    mkdir -p $vtarget
+    # if a Makefile was created by configure, use it, else the top level Makefile
+    [ -f $vtarget/Makefile ] || makefile="-f $srcdir/Makefile"
+    make -C $vtarget $makefile install DESTDIR="$srcdir/debian/$package" PG_CONFIG="$pgc" VPATH="$srcdir"
 }
 
 clean() {
     prepare_env $1
-    make clean PG_CONFIG="$pgc"
+
+    # if a Makefile was created by configure, use it, else the top level Makefile
+    [ -f $vtarget/Makefile ] || makefile="-f $srcdir/Makefile"
+    [ -d $vtarget ] && make -C $vtarget clean $makefile DESTDIR="$srcdir/debian/$package" PG_CONFIG="$pgc" VPATH="$srcdir"
     rm -rf $vtarget
 }
 
 versions() {
+    [ -e /usr/share/postgresql-common/supported-versions ] ||
+	die "/usr/share/postgresql-common/supported-versions not found"
+    [ -e $srcdir/debian/pgversions ] || die "$srcdir/debian/pgversions not found"
     for v in `/usr/share/postgresql-common/supported-versions`
     do
-	grep -q "^$v" $srcdir/debian/pgversions && echo $v
+	if grep -q "^$v" $srcdir/debian/pgversions ; then echo $v ; fi
     done
 }
 
-for v in `versions`
+[ "$srcdir" ] || die "syntax: pg_buildext <action> <srcdir> ..."
+[ -d $srcdir ] || die "no such directory '$srcdir'"
+
+VERSIONS=`versions`
+
+for v in $VERSIONS
 do
     case "$action" in
 	"supported-versions")
 	    echo $v
 	    ;;
 
-	build|clean)
+	configure|build|install|clean)
+	    [ "$target" ] || die "syntax: pg_buildext $action <srcdir> <target> ..."
 	    # be verbose?
 	    $action $v
 	    ;;
 
 	*)
-	    echo "$0: unsupported $action."
+	    die "unsupported $action."
 	    ;;
     esac
 done
-
-exit 0
-
-# POD follows here
-
-=head1 NAME
-
-pg_buildext - Build and install a PostgreSQL extension
-
-=head1 SYNOPSIS
-
-B<pg_buildext> I<action> I<srcdir> I<target> I<opts>
-
-=head1 DESCRIPTION
-
-B<pg_buildext> is a script that will build a PostgreSQL extension in a
-C<VPATH> way. It only supports the B<build> and B<clean> actions, and will
-choose to build the versions known in C<debian/pgversions> and in
-C</usr/share/postgresql-common/supported-versions>.
-
-=head1 OPTIONS
-
-=over 4
-
-=item B<action>
-
-Either I<clean> or I<build>.
-
-=item B<srcdir>
-
-Where to find the extension sources, including the C<debian> subdirectory.
-
-=item B<target>
-
-The target directory where to build the sources, it will get created for you
-if it does not exist. If the B<target> contains a C<%v> sign, it will get
-replaced by the specific version of PostgreSQL being built against.
-
-=item B<opts>
-
-Custom C<CFLAGS> options to use for the build.
-
-=back
-
-=head1 AUTHOR
-
-Dimitri Fontaine L<E<lt>dim@tapoueh.orgE<gt>>
