git-debimport postgresql-common_160.tar.xz

diff --git a/debian/maintscripts-functions b/debian/maintscripts-functions
--- a/debian/maintscripts-functions
+++ b/debian/maintscripts-functions
@@ -1,23 +1,57 @@
 # This file contains common functionality for all postgresql server
 # package maintainer scripts.
 
-# arguments: version package master
+# arguments: version master package [package]
 _link_manpages() {
-    MANS=$(unset GREP_OPTIONS; dpkg -L $2|egrep '/man/.*\.[1-9](\.gz)?$' | grep -v "$3")
+    MANS=$(unset GREP_OPTIONS; dpkg -L $3 $4 $5 2>/dev/null|egrep '/man/.*\.[1-9](\.gz)?$' | grep -v "$2") || true
+    [ -n "$MANS" ] || return 0
+
     SLAVES=$(for i in $MANS; do TARGET=$(echo $i | sed "s/postgresql\/$1\///"); echo -n " --slave $TARGET $(basename $i) $i"; done)
-    update-alternatives --install /usr/share/man/man1/$3 \
-	$3 /usr/share/postgresql/$1/man/man1/$3 \
+    # pg_basebackup once moved from server to client; upgrades are still
+    # affected by this for quite a while, so remove this alternative before
+    # reinstalling it to avoid failure. This needs to be kept until we stop
+    # supporting upgrades from -9.1.
+    if [ "$2" = "psql.1.gz" ]; then
+	OUT=$(LC_ALL=C update-alternatives --display postmaster.1.gz 2> /dev/null) || true
+	if [ "${OUT#*auto mode}" != "$OUT" ] && [ "${OUT#*pg_basebackup.1.gz}" != "$OUT" ]; then
+            echo "Adjusting postmaster.1.gz alternatives for pg_basebackup move..."
+	    update-alternatives --remove postmaster.1.gz /usr/share/postgresql/9.1/man/man1/postmaster.1.gz
+	fi
+    fi
+
+    section=$(echo "$2" | sed -e 's/.*\.\(.*\)\..*/man\1/')
+    update-alternatives --install /usr/share/man/$section/$2 \
+	$2 /usr/share/postgresql/$1/man/$section/$2 \
 	$(echo "$1" | tr -cd 0-9) $SLAVES
 }
 
+# arguments: version master
 _unlink_manpages() {
-    update-alternatives --remove $3 /usr/share/postgresql/$1/man/man1/$3
+    section=$(echo "$2" | sed -e 's/.*\.\(.*\)\..*/man\1/')
+    update-alternatives --remove $2 /usr/share/postgresql/$1/man/$section/$2
 }
 
 _remove_tsearch() {
    if [ -e /usr/share/postgresql/$1/tsearch_data ]; then
        find /usr/share/postgresql/$1/tsearch_data -type l \( -name '*.dict' -o -name '*.affix' \) -exec rm '{}' \;
    fi
+}
+
+# Determine and set system's default locale; we do not want to trust the
+# environment here, as ssh and sudo both propagate the user's locale from
+# potentially a remote host, and that might not even exist; also, we want to be
+# predictable.  /etc/default/locale overrides /etc/environment. Note that
+# /etc/environment is not a shell script, so we must be careful with parsing.
+set_system_locale() {
+    loc_vars="LC_COLLATE LC_CTYPE LC_MONETARY LC_MESSAGES LC_NUMERIC LC_TIME LC_ALL LANG LANGUAGE"
+    unset $loc_vars
+    for v in $loc_vars; do
+        unset val
+        val=`pam_getenv -l $v` || true
+        [ -z "$val" ] || export $v="$val"
+    done
+    [ -e /etc/default/locale ] && . /etc/default/locale || true
+    export $loc_vars
 }
 
 # arguments: <major version> <most recently configured package version>
@@ -29,16 +63,21 @@ configure_version() {
     [ "$VERSION" ] || { echo "Error: configure_version: need version parameter" >&2; exit 1; }
     if [ ! -d "/etc/postgresql/$VERSION" ] || [ -z "$(ls /etc/postgresql/$VERSION)" ] || \
        [ -z "$(ls /etc/postgresql/$VERSION/*/postgresql.conf 2>/dev/null)" ]; then
-        [ "$2" ] || /usr/bin/pg_createcluster -u postgres $VERSION main || {
-	echo "Error: could not create default cluster. Please create it manually with
+        # skip creating the main cluster when this is not the first install, or
+        # when explicitely disabled ($create is 1/0/"")
+        create=$(perl -I/usr/share/postgresql-common -mPgCommon -e 'print PgCommon::config_bool(PgCommon::get_conf_value 0, 0, "createcluster.conf", "create_main_cluster")')
+        if [ -z "$2" ] && [ "$create" != "0" ]; then
+            set_system_locale
+            /usr/bin/pg_createcluster -u postgres $VERSION main || 
+                echo "Error: could not create default cluster. Please create it manually with
 
   pg_createcluster $VERSION main --start
 
 or a similar command (see 'man pg_createcluster')." >&2
-	}
+        fi
     fi
 
-    _link_manpages "$VERSION" "postgresql-$VERSION" postmaster.1.gz
+    _link_manpages "$VERSION" postmaster.1.gz "postgresql-$1" "postgresql-contrib-$1"
 
     if [ -x /etc/init.d/postgresql ] && [ ! -x /etc/init.d/postgresql-$VERSION ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
@@ -62,23 +101,32 @@ stop_version() {
 }
 
 remove_version() {
-    _unlink_manpages "$1" "postgresql-$1" postmaster.1.gz
+    _unlink_manpages "$1" postmaster.1.gz
     _remove_tsearch "$1"
 }
 
 configure_client_version() {
-    _link_manpages "$1" "postgresql-client-$1" psql.1.gz
+    _link_manpages "$1" psql.1.gz "postgresql-client-$1"
 }
 
 remove_client_version() {
-    _unlink_manpages "$1" "postgresql-client-$1" psql.1.gz
+    _unlink_manpages "$1" psql.1.gz
 }
 
 configure_contrib_version() {
-    :
+    _link_manpages "$1" postmaster.1.gz "postgresql-$1" "postgresql-contrib-$1"
 }
 
 remove_contrib_version() {
-    :
+    # we still want to retain the alternatives for the server packages
+    _link_manpages "$1" postmaster.1.gz "postgresql-$1"
+}
+
+configure_doc_version() {
+    _link_manpages "$1" SPI_connect.3.gz "postgresql-doc-$1"
+}
+
+remove_doc_version() {
+    _unlink_manpages "$1" SPI_connect.3.gz
 }
 
diff --git a/pg_buildext b/pg_buildext
--- a/pg_buildext
+++ b/pg_buildext
@@ -1,16 +1,43 @@
 #!/bin/sh
 #
-# build a PostgreSQL module based on PGXS for give list of supported major
+# build a PostgreSQL module based on PGXS for given list of supported major
 # versions
 #
-# Author: Dimitri Fontaine <dfontaine@hi-media.com>
+# (C) 2010 Dimitri Fontaine <dfontaine@hi-media.com>
+# (C) 2011-2014 Christoph Berg <myon@debian.org>
+#
+#  This program is free software; you can redistribute it and/or modify
+#  it under the terms of the GNU General Public License as published by
+#  the Free Software Foundation; either version 2 of the License, or
+#  (at your option) any later version.
+#
+#  This program is distributed in the hope that it will be useful,
+#  but WITHOUT ANY WARRANTY; without even the implied warranty of
+#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#  GNU General Public License for more details.
 
 set -e
 
+VENVARGS=""
+while getopts "c:i:o:s" opt ; do
+    case $opt in
+	c|i|o) VENVARGS="$VENVARGS -$opt $OPTARG" ;;
+	s) VENVARGS="$VENVARGS -$opt" ;;
+	*) exit 1 ;;
+    esac
+done
+# shift away args
+shift $(($OPTIND - 1))
+
 action="$1"
-srcdir="${2:-`pwd`}"
-target="$3"
-opt="$4"
+if [ -d "$2" ] && [ "$3" ]; then # compat mode: $2 is source directory
+    srcdir="$2"
+    shift
+else
+    srcdir="$PWD"
+fi
+target="$2"
+opt="$3"
 
 die() {
     echo "`basename $0`: error: $*" >&2
@@ -21,7 +48,7 @@ prepare_env() {
     version=$1
     vtarget=`echo $target | sed -e "s:%v:$version:g"`
     pgc="/usr/lib/postgresql/$version/bin/pg_config"
-    [ -e "$pgc" ] || die "$pgc does not exists"
+    [ -e "$pgc" ] || die "$pgc does not exist"
 }
 
 configure() {
@@ -40,7 +67,7 @@ build() {
     mkdir -p $vtarget
     # if a Makefile was created by configure, use it, else the top level Makefile
     [ -f $vtarget/Makefile ] || makefile="-f $srcdir/Makefile"
-    make -C $vtarget $makefile CFLAGS="$cflags" DESTDIR="$srcdir/debian/$package" PG_CONFIG="$pgc" VPATH="$srcdir"
+    make -C $vtarget $makefile CFLAGS="$cflags" DESTDIR="$srcdir/debian/$package" PG_CONFIG="$pgc" VPATH="$srcdir" srcdir="$srcdir" USE_PGXS=1
 }
 
 install() {
@@ -50,7 +77,7 @@ install() {
     mkdir -p $vtarget
     # if a Makefile was created by configure, use it, else the top level Makefile
     [ -f $vtarget/Makefile ] || makefile="-f $srcdir/Makefile"
-    make -C $vtarget $makefile install DESTDIR="$srcdir/debian/$package" PG_CONFIG="$pgc" VPATH="$srcdir"
+    make -C $vtarget $makefile install DESTDIR="$srcdir/debian/$package" PG_CONFIG="$pgc" VPATH="$srcdir" srcdir="$srcdir" USE_PGXS=1
 }
 
 clean() {
@@ -58,22 +85,89 @@ clean() {
 
     # if a Makefile was created by configure, use it, else the top level Makefile
     [ -f $vtarget/Makefile ] || makefile="-f $srcdir/Makefile"
-    [ -d $vtarget ] && make -C $vtarget clean $makefile DESTDIR="$srcdir/debian/$package" PG_CONFIG="$pgc" VPATH="$srcdir"
+    [ -d $vtarget ] && make -C $vtarget clean $makefile DESTDIR="$srcdir/debian/$package" PG_CONFIG="$pgc" VPATH="$srcdir" srcdir="$srcdir" USE_PGXS=1
     rm -rf $vtarget
+}
+
+loop() {
+    echo "### $1 ###"
+    prepare_env $1
+    package=$(echo $target | sed -e "s:%v:$version:g")
+
+    echo "# $1: make clean"
+    make clean            DESTDIR="$PWD/debian/$package" PG_CONFIG="$pgc" USE_PGXS=1
+    echo "# $1: make"
+    make CFLAGS="$cflags" DESTDIR="$PWD/debian/$package" PG_CONFIG="$pgc" USE_PGXS=1
+    echo "# $1: make install"
+    make install          DESTDIR="$PWD/debian/$package" PG_CONFIG="$pgc" USE_PGXS=1
+    echo "### done $1 ###"
+}
+
+installcheck() {
+    prepare_env $1
+
+    if [ "$target" ]; then # if target is given, use it, else stay in the top source dir
+	# if a Makefile was created by configure, use it, else the top level Makefile
+	[ -f $vtarget/Makefile ] || makefile="-f $srcdir/Makefile"
+	if ! pg_virtualenv $VENVARGS -v $1 \
+	    make -C $vtarget $makefile installcheck \
+		PG_CONFIG="$pgc" VPATH="$srcdir" srcdir="$srcdir" USE_PGXS=1; then
+	    if [ -r $vtarget/regression.diffs ]; then
+		echo "**** $vtarget/regression.diffs ****"
+		cat $vtarget/regression.diffs
+	    fi
+	    exit 1
+	fi
+    else
+	if ! pg_virtualenv $VENVARGS -v $1 \
+	    make installcheck PG_CONFIG="$pgc" srcdir="$srcdir" USE_PGXS=1; then
+	    if [ -r regression.diffs ]; then
+		echo "**** regression.diffs ****"
+		cat regression.diffs
+	    fi
+	    exit 1
+	fi
+    fi
 }
 
 versions() {
     [ -e /usr/share/postgresql-common/supported-versions ] ||
 	die "/usr/share/postgresql-common/supported-versions not found"
-    [ -e $srcdir/debian/pgversions ] || die "$srcdir/debian/pgversions not found"
-    for v in `/usr/share/postgresql-common/supported-versions`
-    do
-	if grep -q "^$v" $srcdir/debian/pgversions ; then echo $v ; fi
-    done
+    [ -e debian/pgversions ] || die "debian/pgversions not found"
+    supported_versions=$(/usr/share/postgresql-common/supported-versions)
+    while read version; do
+	case $version in
+	    all) echo "$supported_versions" ;;
+	    [1-9]*+)
+		for sup_version in $supported_versions; do
+		    if expr $(echo "$version" | tr -d +) '<=' $sup_version > /dev/null; then echo "$sup_version"; fi
+		done ;;
+	    [1-9]*)
+		for sup_version in $supported_versions; do
+		    if [ "$version" = "$sup_version" ]; then echo "$sup_version"; fi
+		done ;;
+	    '#'*) ;;
+	    '') ;;
+	    *) echo "Syntax error in debian/pgversions: $version" >&2 ;;
+	esac
+    done < debian/pgversions
 }
 
-[ "$srcdir" ] || die "syntax: pg_buildext <action> <srcdir> ..."
-[ -d $srcdir ] || die "no such directory '$srcdir'"
+# when a version is included in the action, just act on this one (this is
+# useful if some extra work needs to be done per version, so the loop over
+# supported-versions needs to be in the script calling pg_buildext)
+
+case $action in
+    configure-*|build-*|install-*|clean-*|installcheck-*)
+	a=${action%%-*}
+	v=${action##$a-}
+	echo "### $a $v ###"
+	$a $v
+	exit
+	;;
+esac
+
+# loop over versions
 
 VERSIONS=`versions`
 
@@ -84,14 +178,19 @@ do
 	    echo $v
 	    ;;
 
-	configure|build|install|clean)
-	    [ "$target" ] || die "syntax: pg_buildext $action <srcdir> <target> ..."
-	    # be verbose?
+	configure|build|install|clean|loop)
+	    [ "$target" ] || die "syntax: pg_buildext $action [...]"
+	    echo "### $action $v ###"
+	    $action $v
+	    ;;
+
+	installcheck)
+	    echo "### $action $v ###"
 	    $action $v
 	    ;;
 
 	*)
-	    die "unsupported $action."
+	    die "unsupported $action"
 	    ;;
     esac
 done
diff --git a/testsuite b/testsuite
--- a/testsuite
+++ b/testsuite
@@ -1,8 +1,10 @@
-#!/bin/sh -e
+#!/bin/sh
 
-# Run integration tests (on the installed package).
+# Run integration tests (on the installed package). This happens on unshared
+# tmpfses, so does not interfere with installed clusters.
 #
-# (C) 2005-2009 Martin Pitt <mpitt@debian.org>
+# (C) 2005-2012 Martin Pitt <mpitt@debian.org>
+# (C) 2012-2014 Christoph Berg <myon@debian.org>
 #
 #  This program is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
@@ -14,51 +16,125 @@
 #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #  GNU General Public License for more details.
 
+set -e
+
+# default config
+TESTSDIR="$(dirname $0)/t"
+: ${PG_UMASKS="022 077"}
+
+help ()
+{
+    echo "postgresql-common testsuite"
+    echo "Syntax: $0 [options] [test ...]"
+    echo "    -f number        run tests starting at this number"
+    echo "    -i               install packages for versions specified by -v"
+    echo "    -s               start a shell in the testbed on failure"
+    echo "    -u 'umask ...'   umasks to run testsuite with [default: 022 077]"
+    echo "    -v 'version ...' PostgreSQL versions to test [default: client versions installed]"
+    exit ${1:-0}
+}
+
+# option parsing
+while getopts "hf:isu:v:" opt ; do
+    case $opt in
+        f) FROM="$OPTARG" ;;
+        i) INSTALL=1 ;;
+        h) help ;;
+        s) RUN_SHELL=1 ;;
+        u) PG_UMASKS="$OPTARG" ;;
+        v) export PG_VERSIONS="$OPTARG" ;; # used in t/TestLib.pm
+        *) help 1 ;;
+    esac
+done
+
 if [ "$(id -u)" != 0 ]; then
     echo "Error: this test suite needs to be run as root" >&2
     exit 1
 fi
 
-TESTSDIR="$(dirname $0)/t"
+# install packages for versions specified by -v
+# needs network for apt, so run before unshare
+if [ "${INSTALL:-}" ] && [ -z "${UNSHARED:-}" ]; then
+    for v in $PG_VERSIONS; do
+        apt-get install -y postgresql-contrib-$v \
+            postgresql-plperl-$v \
+            postgresql-plpython-$v \
+            postgresql-plpython3-$v \
+            postgresql-pltcl-$v \
+            postgresql-server-dev-$v
+    done
+    apt-get install -y libecpg-dev \
+        locales \
+        logrotate \
+        procps \
+        netcat-openbsd \
+        hunspell-en-us
+fi
+# requirements on RedHat:
+# perl-Test-Simple perl-Time-HiRes
 
-# always clean up behind us
-trap '
-if [ -d /etc/postgresql.testsuite ]; then 
-    rm -rf /etc/postgresql; 
-    mv /etc/postgresql.testsuite /etc/postgresql;
-fi;
-if [ -d /var/lib/postgresql.testsuite ]; then 
-    rm -rf /var/lib/postgresql;
-    mv /var/lib/postgresql.testsuite /var/lib/postgresql;
-fi;
-if [ -d /var/log/postgresql.testsuite ]; then 
-    rm -rf /var/log/postgresql;
-    mv /var/log/postgresql.testsuite /var/log/postgresql;
-fi' 0 1 2 3 5 7 10 13 15
+# re-exec ourselves through unshare
+if [ -z "$UNSHARED" ]; then
+    UNSHARED=1 exec unshare -uimn -- "$0" "$@"
+fi
 
-# temporarily move away existing clusters
-for v in $(ls /usr/lib/postgresql/); do
-    if [ -x "/etc/init.d/postgresql-$v" ]; then
-        /etc/init.d/postgresql-$v stop
-    fi
-done
+# shift away args
+shift $(($OPTIND - 1))
+
+# use the local pgcommon.sh (either in the build tree or /usr/share/postgresql-common)
+. ./pgcommon.sh
+
+# install locales
+locale_gen \
+    en_US.UTF-8 UTF-8 \
+    ru_RU ISO-8859-5 \
+    ru_RU.UTF-8 UTF-8
+
+# stop currently running clusters
 if [ -x "/etc/init.d/postgresql" ]; then
     /etc/init.d/postgresql stop
 fi
 
-if [ -d /etc/postgresql ]; then 
-    mv /etc/postgresql /etc/postgresql.testsuite;
-fi
-if [ -d /var/lib/postgresql ]; then 
-    mv /var/lib/postgresql /var/lib/postgresql.testsuite;
-fi
-if [ -d /var/log/postgresql ]; then 
-    mv /var/log/postgresql /var/log/postgresql.testsuite;
-    install -d -m 1775 -o root -g postgres /var/log/postgresql
-fi
+# let everything happen in overlay tmpfses to avoid interfering with already
+# existing clusters; this also speeds up testing
+mount --make-rprivate / 2> /dev/null || : # reset / to private mounts (systemd changes this to shared)
+dirs="/etc/postgresql /etc/postgresql-common /var/lib/postgresql /var/log/postgresql /var/run/postgresql /dev/shm"
+created_dirs=""
+for d in $dirs; do
+    if ! [ -d $d ]; then
+        created_dirs="$created_dirs $d"
+        mkdir -p $d
+    fi
+    mount -n -t tmpfs -o mode=755 tmpfs $d
+done
+# clean up created directories after us
+cleanup () {
+    umount $dirs
+    if [ "$created_dirs" ]; then
+        rmdir --ignore-fail-on-non-empty -p $created_dirs
+    fi
+}
+trap "cleanup" 0 HUP INT QUIT ILL ABRT PIPE TERM
+chown root:postgres /var/log/postgresql
+chmod 1775 /var/log/postgresql
+chown postgres:postgres /var/run/postgresql
+chmod 2775 /var/run/postgresql
+chmod 1777 /dev/shm
+
+# the RPM packages enable the logging_collector by default, which the testsuite
+# doesn't like. We disable it unconditionally here.
+echo "logging_collector = off" >> /etc/postgresql-common/createcluster.conf
 
 # reset core limit for pg_ctl tests
 ulimit -S -c 0
+
+# start localhost interface
+ifconfig lo up || true
+
+# set environment
+unset TMPDIR
+unset LC_ALL
+export LANG=en_US.utf8
 
 # set variables which cause taint check errors
 export IFS=' '
@@ -70,15 +146,26 @@ if [ $# -eq 0 ]; then
     set -- $TESTSDIR/*.t
 fi
 
-echo "====== Running all tests with default umask 022 ======="
-umask 022
-for T; do
-    echo "=== Running test `basename $T`... ==="
-    perl $T
-done
-echo "====== Running all tests with tight umask 077 ======="
-umask 077
-for T; do
-    echo "=== Running test `basename $T`... ==="
-    perl $T
+for U in $PG_UMASKS; do
+    case $U in
+        022) TYPE="default" ;;
+        077) TYPE="tight" ;;
+        *) TYPE="custom" ;;
+    esac
+
+    echo "====== Running all tests with $TYPE umask $U ======="
+    umask $U
+    for T; do
+        TBASE=${T##*/}
+        [ "$FROM" ] && [ "${TBASE%%_*}" -lt "$FROM" ] && continue
+        echo "=== Running test $TBASE ... ==="
+        perl $T || {
+            EXIT=$?
+            if [ "${RUN_SHELL:-}" ]; then
+                echo "*** $TBASE failed with status $EXIT, dropping you into a shell in the testbed ***"
+                ${SHELL:-/bin/sh}
+            fi
+            exit $EXIT
+        }
+    done
 done
